/*
 * RenamerAboutBox.java
 */

package renamer.UI;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.jdesktop.application.Action;
import renamer.SRC.AppInfo;
import renamer.SRC.Model;

class ImagePanel extends JPanel {
    private static final long serialVersionUID = 3431561270624351342L;

    private Image img;

    public ImagePanel(URL url) {
        this( new ImageIcon( url ).getImage(), 0, 0 );
    }

    public ImagePanel(URL url, int width, int height) {
        this( new ImageIcon( url ).getImage(), width, height );
    }

    public ImagePanel(Image img, int width, int height) {
        this.img = img;

        if ( width == 0 ) {
            width = img.getWidth( null );
        }

        if ( height == 0 ) {
            height = img.getHeight( null );
        }
        
        Dimension size = new Dimension( width, height );
        this.setPreferredSize( size );
        this.setMinimumSize( size );
        this.setMaximumSize( size );
        this.setSize( size);
        this.img = img.getScaledInstance( width, height, Image.SCALE_SMOOTH );
        this.setLayout( null );
    }

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage( img, 0, 0, null );
    }

}
public class RenamerAboutBox extends javax.swing.JDialog implements KeyListener {
    public final String[] AboutMsg = { "About", "Acerca de" };
    public final String[] VersionMsg = { "Version:", "Versión:" };
    public final String[] VendorMsg = { "Author e.mail:", "eMail del Autor:" };
    public final String[] HomepageMsg = { "Web page:", "Página web:",  };
    public final String[] AppDescMsg = { AppInfo.AppDesc_EN, AppInfo.AppDesc_ES };
    public final String[] btCloseLbl = { "Close", "Cerrar" };

    public RenamerAboutBox(java.awt.Frame parent, Model m) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton( closeButton );

        // Details
        setTitle( AboutMsg[ m.getLanguage().ordinal() ] + "... " + AppInfo.Name );
        closeButton.setText( btCloseLbl[ m.getLanguage().ordinal() ] );
        closeButton.setMnemonic( 'c' );

        // Icon image in the dialog
        ImagePanel ip = new ImagePanel(
                getClass().getResource( "/" + RenamerView.EtqDirRes + "/" + RenamerView.EtqIconName ),
                56,
                56
        );
        this.getContentPane().add( ip );

        // Info
        versionLabel.setText( VersionMsg[ m.getLanguage().ordinal() ] );
        vendorLabel.setText( VendorMsg[ m.getLanguage().ordinal() ] );
        homepageLabel.setText( HomepageMsg[ m.getLanguage().ordinal() ] );
        appDescLabel.setText( AppDescMsg[ m.getLanguage().ordinal() ] );

        // Data
        appVendorLabel.setText( AppInfo.Author );
        appHomepageLabel.setText( AppInfo.Url );
        appVersionLabel.setText( AppInfo.Version );
        appTitleLabel.setText( AppInfo.Name );

        // Listener
        closeButton.addKeyListener( this );
    }
    
    @Action public void closeAboutBox() {
        this.setVisible( false );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        appTitleLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        appVersionLabel = new javax.swing.JLabel();
        vendorLabel = new javax.swing.JLabel();
        appVendorLabel = new javax.swing.JLabel();
        homepageLabel = new javax.swing.JLabel();
        appHomepageLabel = new javax.swing.JLabel();
        appDescLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(renamer.UI.RenamerApp.class).getContext().getActionMap(RenamerAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(renamer.UI.RenamerApp.class).getContext().getResourceMap(RenamerAboutBox.class);
        appTitleLabel.setText(resourceMap.getString("appTitleLabel.text")); // NOI18N
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
        versionLabel.setName("versionLabel"); // NOI18N

        appVersionLabel.setName("appVersionLabel"); // NOI18N

        vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
        vendorLabel.setName("vendorLabel"); // NOI18N

        appVendorLabel.setName("appVendorLabel"); // NOI18N

        homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
        homepageLabel.setName("homepageLabel"); // NOI18N

        appHomepageLabel.setName("appHomepageLabel"); // NOI18N

        appDescLabel.setName("appDescLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(versionLabel)
                            .addComponent(vendorLabel)
                            .addComponent(homepageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appVersionLabel)
                            .addComponent(appVendorLabel)
                            .addComponent(appHomepageLabel)))
                    .addComponent(appDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appTitleLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(appDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(appVersionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorLabel)
                    .addComponent(appVendorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homepageLabel)
                    .addComponent(appHomepageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appDescLabel;
    private javax.swing.JLabel appHomepageLabel;
    private javax.swing.JLabel appTitleLabel;
    private javax.swing.JLabel appVendorLabel;
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel homepageLabel;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

    public void keyTyped(KeyEvent evt) {
    }

    public void keyPressed(KeyEvent evt) {
    }

    public void keyReleased(KeyEvent evt) {
        if ( evt.getKeyCode() == KeyEvent.VK_ESCAPE ) {
            closeAboutBox();
        }
    }
    
}
